# CI-0117 Programacion concurrente
# Luis Diego Esquivel - B82806
# Andres David Ramirez - B86426
#

all: sequencesMPI.out


sequencesMPI.out: sequencesMPI.cc 
	mpiCC adn.h adn.cc sequencesMPI.cc -o sequencesMPI.out 

