all: 
	g++ medios.cc Punto.cc Punto.h VectorPuntos.cc VectorPuntos.h -o medios.out -fopenmp

medios.out: medios.cc
	g++ medios.cc Punto.cc Punto.h VectorPuntos.cc VectorPuntos.h -o medios.out -fopenmp

